"""create a profile picture model

Revision ID: 2b87416a7105
Revises: 3f0d3f31c933
Create Date: 2024-11-11 15:41:22.675651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b87416a7105'
down_revision = '3f0d3f31c933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userPics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_route', sa.String(), server_default='https://static.vecteezy.com/system/resources/thumbnails/008/442/086/small/illustration-of-human-icon-user-symbol-icon-modern-design-on-blank-background-free-vector.jpg', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userPics_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userPics')
    # ### end Alembic commands ###
