"""create initial tables

Revision ID: 927438c2a31f
Revises: 
Create Date: 2024-11-09 20:16:24.271913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927438c2a31f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('image', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub_title', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('background_image', sa.String(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_actors_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_directors_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_media_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['media_id'], ['media_types.id'], name=op.f('fk_media_genres_media_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_time_hours', sa.Integer(), nullable=False),
    sa.Column('run_time_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['media_types.id'], name=op.f('fk_movies_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_types.id'], name=op.f('fk_tv_shows_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_users_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_genres_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_viewers_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    op.drop_table('users_genres')
    op.drop_table('tv_shows')
    op.drop_table('movies')
    op.drop_table('media_genres')
    op.drop_table('directors')
    op.drop_table('actors')
    op.drop_table('users')
    op.drop_table('media_types')
    op.drop_table('genres')
    # ### end Alembic commands ###
