"""add film cast table

Revision ID: e7cfae9c505e
Revises: 6136753225f0
Create Date: 2024-11-27 19:31:53.998967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cfae9c505e'
down_revision = '6136753225f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('billing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_media_cast_actor_id_users')),
    sa.ForeignKeyConstraint(['media_id'], ['media_types.id'], name=op.f('fk_media_cast_media_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_cast')
    # ### end Alembic commands ###
